package com.zerotap.domain.model

import java.util.UUID

/**
 * Core incident model representing a detected safety event.
 */
data class Incident(
    val id: String = UUID.randomUUID().toString(),
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val riskScore: Float,
    val riskState: RiskState,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val contributingSignals: List<RiskSignal> = emptyList(),
    val evidenceId: String? = null,
    val status: IncidentStatus = IncidentStatus.DETECTED,
    val summary: String? = null
)

/**
 * Summary generated by the LocalIncidentSummarizer.
 */
data class IncidentSummary(
    val incidentId: String,
    val summary: String,
    val generatedAt: Long = System.currentTimeMillis(),
    val engineLabel: String = "development"
)

/**
 * Evidence metadata stored in Room (actual evidence is encrypted on disk).
 */
data class EvidencePackage(
    val id: String = UUID.randomUUID().toString(),
    val incidentId: String,
    val createdAt: Long = System.currentTimeMillis(),
    val motionSampleCount: Int = 0,
    val locationSampleCount: Int = 0,
    val audioChunkCount: Int = 0,
    val encryptionKeyAlias: String = "",
    val storagePath: String? = null,
    val sizeBytes: Long = 0
)
